sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - node_modules
    - ~/.cache
env:
  - CI=true

install:
  - npm install

script:
  - npm run test:integrate
  - npm run test:unit

after_success:
  - npm run coverage

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_PUBLISH_KEY -d ./build
  skip_cleanup: true

branches:
  only: master
